baseURL = "https://kerrrry.ca"
languageCode = "en-us"
title = "Kerry Smart"
theme = "cactus"
copyright = "Kerry Smart"
author = "Kerry Smart"

[params]
    # description = "Hello - I'm Kerry and I love to craft and make things.  I'm currently focused on cross stitching and web development."
    rss = true
    #https://example.com/index.xml is RSS feed
    css = ["css/contact.css", "css/gallery-page.css", "css/gallery.css"]  
    name = "Kerry Smart"
    # mainSection = "categories"  #changes section on main page
    mainSectionTitle = "Recent Cross Stitch"
    showAllPostsOnHomePage = false
    postsOnHomePage = 6
    tagsOverview = false

# ----------- nav ------------

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Cross Stitch Gallery"
  url = "/gallery"
  weight = 3


# [[menu.main]]
#   name = "Tags"
#   url = "/tags"
#   weight = 3

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 4

[[menu.main]]
  name = "Hire Me"
  url = "/hire"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 6



# [[menu.main]]
#   name = "Tech Site"
#   url = "https://kerrysmart.ca"
#   weight = 7

# [[menu.main]]
#   name = "RSS"
#   url = "/index.xml"
#   weight = 7



# ------------ socials -----------------

[[params.social]]
  fa_name = "external-link-alt"
  name = "Web Dev"
  link = "https://kerrysmart.ca"

[[params.social]]
  fa_name = "email"
  name = "Email"
  link = "kerry.z.smart@gmail.com"

[[params.social]]
  fa_name = "github"
  name = "Github"
  link = "https://github.com/zilliah"

 [[params.social]]
  fa_name = "instagram"
  name = "Instagram"
  link = "https://www.instagram.com/verypuzzles/"


[[params.social]]
  fa_name = "ravelry"
  name = "Ravelry"
  link = "https://www.ravelry.com/people/zilliah"

[[params.social]]
  fa_name = "linkedin"
  name = "LinkedIn"
  link = "https://www.linkedin.com/in/kerryzsmart/"


[[params.social]]
  fa_name = "rss"
  name = "RSS"
  link = "/index.xml"


 

# ----------------- categories (taken over projects) -------------------