baseURL = "https://kerryr.netlify.app/"
languageCode = "en-us"
title = "Kerry Smart"
theme = "cactus"
copyright = "Kerry Smart"

[params]
    # description = "Hello - I'm Kerry and I love to craft and make things.  I'm currently focused on cross stitching and web development."
    rss = true
    #https://example.com/index.xml is RSS feed
    # css = ["css/kstyles.css"]  //can add custom css but am just editing the theme scss...
    name = "Kerry Smart"
    # mainSection = "categories"  #changes section on main page
    mainSectionTitle = "Posts"
    showAllPostsOnHomePage = false
    postsOnHomePage = 6
    tagsOverview = true

# ----------- nav ------------

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 2

# [[menu.main]]
#   name = "Projects"
#   url = "/projects"
#   weight = 3


# [[menu.main]]
#   name = "Tags"
#   url = "/tags"
#   weight = 3

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 4

[[menu.main]]
  name = "Hire Me"
  url = "/hire"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 6



# [[menu.main]]
#   name = "Tech Site"
#   url = "https://kerrysmart.ca"
#   weight = 7

[[menu.main]]
  name = "RSS"
  url = "/index.xml"
  weight = 7



# ------------ socials -----------------

#  [[params.social]]
#   name = "instagram"
#   link = "https://www.instagram.com/vitreousfabric/"

# [[params.social]]
#   name = "github"
#   link = "https://github.com/zilliah"

# [[params.social]]
#   name = "linkedin"
#   link = "https://www.linkedin.com/in/kerryzsmart/"


# [[params.social]]
#   name = "email"
#   link = "kerry.z.smart@gmail.com"


# ----------------- categories (taken over projects) -------------------